### ISSUE TITLE
Milestone: 2.0

### ISSUE THREAD

**Issue by cydrobolt** [cydrobolt/polr#66]
As we slowly approach version 2.0, there are many issues that need to be addressed before we can release a stable version of our next milestone.

Improvements:
- [x] Use Lumen
- [x] Use a templating system (Blade)
- [x] Use Eloquent ORM
- [ ] Show tooltips to fetch more info in the admin panel
- [x] Paginate the admin panel and the "my links" area #58 
- [x] Improve the current `anotice` and `unotice` system
- [x] Allow themes to be set per-user
- [x] Allow Link Deletion
- [x] Mobile Responsiveness

Bugs:

- [x] Filter CSRF #57 

See branch polr/2.0-devel

**Comment by fwilson42** [comment]
Should we support localization/translation?

**Comment by Cydrobolt** [comment]
@fwilson42 #51

**Comment by kfrankperson** [comment]
What about moving the project over to the PHP framework Laravel ?

It has most of the things listed above by default :+1:

**Comment by Cydrobolt** [comment]
@kfrankperson Mostly for performance issues. We're aiming to be minimalist, and Laravel brings a ton of baggage we don't want. It also breaks compatibility for shared hosting, and increases the amount of work to get working.

**Comment by kfrankperson** [comment]
Most good hosts now support composer, and if you build it right all you would need to do is SSH into the box, Composer install it and then do a installer via the web like you already have.

There's some much of the code that you guys need that has already been done and looked at by thousands of people in the Laravel project, and i used daily. Looking at all the issues for the project currently most are by default in Laravel

https://github.com/cachethq/Cachet

There installer is soooo simple and easy ( Apart from the assets stuff which does make it complex but personally I wouldn't do that, get to complex fast )

**Comment by Cydrobolt** [comment]
Yeah, I understand that some hosts support composer, but we don't need the whole Laravel package. It is really bulky and transferring to it would break our philosophy of minimalism.

**Comment by Cydrobolt** [comment]
Right now, the project structure is certainly not the greatest. There'll be a lot of revamp to do.

**Comment by j0k3r** [comment]
@Cydrobolt you don't need to switch to Laravel for that. Why don't you use Silex or only some Symfony component?

Nowadays *raw* php project slow down contributor because it's always hard to understand a new project which follow ideas (structure, convention, etc ..) of one developper. Using a framework (even a minimalist one) will break that point.

It will also simplify test integration and avoid regression, etc ..

**Comment by kfrankperson** [comment]
You could even use Lumen - http://lumen.laravel.com/

**Comment by Cydrobolt** [comment]
@kfrankperson @j0k3r
Sounds like a great idea. I'll take a look at both of them and see if I can integrate those

**Comment by WikiCopter** [comment]
What is the projected release date for polr 2.0?

**Comment by Cydrobolt** [comment]
@WikiCopter I don't think we have a projected release date yet. It's a big transition, and we hope to integrate some framework or figure out a way to integrate all of our changes into the app without adding in any frameworks. 

Hopefully we can do this quickly, despite PHP's imposed difficulty on refactoring large amounts of legacy/different code. :smile:

**Comment by cydrobolt** [comment]
2.0.0 beta 1 is now available at https://github.com/cydrobolt/polr/releases/tag/2.0.0b1
